#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

language: generic

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda # makes travis build fail
  # Useful for debugging any issues with conda
  - conda info -a
  - conda init bash
  - export CONDA_BASE=$(conda info --base)
  - source $CONDA_BASE/etc/profile.d/conda.sh

  # Install mamba as a dramatically faster conda replacement. Specifying a
  # fixed version makes the installation of mamba itself much faster, and
  # avoids potential breakage due to changes in mamba behaviour.
  - conda install mamba=0.1.2 -c conda-forge

  # Environments created by mamba can't be referenced by name from conda
  # (presumably a bug), so we use an explicit path instead.
  - mamba env create --prefix $HOME/mamba-env --file environment.yml
  - conda activate $HOME/mamba-env
  - conda list
  - python setup.py install 

  # Setting NUMBA_DISABLE_JIT=1 makes unit tests way too slow, so we accept less code coverage here
  # - export NUMBA_DISABLE_JIT=1
  - py.test -v --cov=xcube

after_success:
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
