name: xcube-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.6
  #
  # runtime dependencies
  #
  - boto3=1.7.51
  - botocore=1.10.51
  - click=7.0
  - dask=0.17.2
  - gdal=2.2.4
  - matplotlib=2.2.2
  - numpy=1.14.3
  - pandas=0.23.1
  - pyyaml=3.12
  - s3fs=0.1.5
  - xarray=0.10.7
  - zarr=2.2.0
  #
  # development dependencies
  #
  - pytest=3.5.1
  - pytest-cov=2.5.1
  - flake8=3.5.0