name: xcube
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.6
  # Required
  - affine >=2.2
  - click >=7.0
  - cmocean >=2.0
  # Memory leak in dask > 2021.3.1
  - dask =2021.3.1
  - fiona >=1.8
  - gdal >=3.0
  - geopandas >=0.8
  - jdcal >=1.4.1
  - jsonschema >=3.2.0
  - matplotlib-base >=3.0
  - netcdf4 >=1.5.0
  - numba >=0.52
  - numpy >=1.16
  # Pandas 1.3+ does not work with xarray < 0.19
  - pandas >=1.2,<1.3
  - pillow >=6.0
  - pyjwt >=1.7
  - pyproj >=3.0
  - pyyaml >=5.4
  - rasterio >=1.2
  - requests >=2.25
  - requests-oauthlib >=1.3
  - s3fs >=0.5.2
  - scipy >=1.6.0
  - setuptools >=41.0
  - shapely >=1.6
  # for python-jsonschema date-time format validation
  - strict-rfc3339 >=0.7
  - tornado >=6.0
  - urllib3 >=1.26
  # TODO: a lot of tests fail with 0.19
  # Therefore pin to 0.18.2
  - xarray =0.18.2
  - zarr >=2.6.1
  # Testing
  - flake8 >=3.7
  - moto >=1.3
  - pytest >=4.4
  - pytest-cov >=2.6
  - requests-mock >=1.8.0
