
dataset_cache_size: 100M

data_stores:
  - store_id: file
    store_params:
      root: examples/serve/demo
    datasets:
      - data_id: cube-1-250-250.levels
      - data_id: cube-5-100-200.zarr
#  - store_id: s3
#    store_params:
#      root: xcube-examples
#    datasets:
#      - data_id: OLCI-SNS-RAW-CUBE-2.zarr
