
dataset_cache_size: 100M

DataStores:
  - Identifier: test
    StoreId: file
    StoreParams:
      root: examples/serve/demo
    Datasets:
      - Path: "cube-1-250-250.zarr"
        Identifier: "Cube 1"
        Style: "default"
      - Path: "cube-5-100-200.zarr"
        Identifier: "Cube 5"
        Style: "default"
      - Path: "*.levels"
        Style: "default"
