Authentication:
  Domain: kc.brockmann-consult.de/auth/realms/AVL
  Audience: avl-xc-api

AccessControl:
  RequiredScopes:
    # Clients must be granted permission "read:dataset:l2c-cyanoalert-olci-balt" in auth0
    # to be able to see this dataset
    - "read:dataset:{Dataset}"
    # Clients must be granted permission "read:variable:chl_c2rcc" in auth0
    # to be able to see variable "chl_c2rcc"
    # - "read:variable:{Variable}"

DatasetAttribution:
  - "© by Brockmann Consult GmbH 2022, contains modified Copernicus Data 2019, processed by ESA"
  - "© by EU H2020 CyanoAlert project"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: avl
    StoreId: s3
    StoreParams:
      root: agriculture-vlab-user
      max_depth: 2
      storage_options:
        anon: false
    Datasets:
      - Path: "*.zarr"
      - Path: "*.levels"

ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Norman Fomferra"
    PositionName: "Senior Software Engineer"
    ContactInfo:
      Phone:
        Voice: "+49 40 696 389 300"
        Facsimile: "+49 40 696 389 399"
      Address:
        DeliveryPoint: "Chrysanderstr. 1"
        City: "Hamburg"
        AdministrativeArea: "Hamburg"
        PostalCode: "21029"
        Country: "Germany"
        ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"
