Authentication:
  Domain: kc.brockmann-consult.de/auth/realms/AVL
  Audience: avl-xc-viewer

DatasetAttribution:
  - "© by Brockmann Consult GmbH 2020, contains modified Copernicus Data 2019, processed by ESA"
  - "© by EU H2020 CyanoAlert project"

DatasetChunkCacheSize: 100M

Datasets:
  # Will only appear for unauthorized clients
  - Identifier: local
    Title: "Local OLCI L2C cube for region SNS"
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: file
    Path: cube-1-250-250.levels
    Style: default
    TimeSeriesDataset: local_ts
    Augmentation:
      Path: "compute_extra_vars.py"
      Function: "compute_variables"
      InputParameters:
        factor_chl: 0.2
        factor_tsm: 0.7
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube
    AccessControl:
      IsSubstitute: true

# To create a tile-optimized pyramid version of "./cube-1-250-250.zarr"
# run following command in this directory:
#
# $ xcube level ./cube-1-250-250.zarr
#
#  - Identifier: local_levels
#    Title: "Local OLCI L2C cube for region SNS (levels)"
#    BoundingBox: [0.0, 50, 5.0, 52.5]
#    FileSystem: file
#    Path: cube-1-250-250.levels
#    Style: default

  # Will not appear at all, because it is a "hidden" resource
  - Identifier: local_ts
    Title: "'local' optimized for time-series"
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: file
    Path: cube-5-100-200.zarr
    Hidden: true
    Style: default

  # Will only appear for bearer tokens with "read:datasets" scope
  - Identifier: remote
    Title: Remote OLCI L2C cube for region SNS
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: s3
    Endpoint: "https://s3.eu-central-1.amazonaws.com"
    Path: "xcube-examples/OLCI-SNS-RAW-CUBE-2.zarr"
    Region: "eu-central-1"
    Anonymous: true
    Style: default
    ChunkCacheSize: 250M
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube
    AccessControl:
      RequiredScopes:
        - read:datasets

  # Will only appear for unauthorized clients
  - Identifier: local_1w
    Title: OLCI weekly L3 cube for region SNS computed from local L2C cube
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: memory
    Path: "resample_in_time.py"
    Function: "compute_dataset"
    InputDatasets: ["local"]
    InputParameters:
      period: "1W"
      incl_stdev: True
    Style: default
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube
    AccessControl:
      IsSubstitute: True

  # Will only appear for bearer tokens with "read:datasets" scope
  - Identifier: remote_1w
    Title: OLCI weekly L3 cube for region SNS computed from remote L2C cube
    BoundingBox: [0.0, 50, 5.0, 52.5]
    FileSystem: memory
    Path: "resample_in_time.py"
    Function: "compute_dataset"
    InputDatasets: ["remote"]
    InputParameters:
      period: "1W"
      incl_stdev: True
    Style: default
    PlaceGroups:
      - PlaceGroupRef: inside-cube
      - PlaceGroupRef: outside-cube
    AccessControl:
      RequiredScopes:
        - read:datasets

PlaceGroups:
  - Identifier: inside-cube
    Title: Places inside the cube
    Path: "places/inside-cube.geojson"
    Join:
      Property: "ID"
      Path: "places/inside-cube-media.geojson"
    PropertyMapping:
      image: "${base_url}/images/inside-cube/${image}"
  - Identifier: outside-cube
    Title: Places outside the cube
    Path: "places/outside-cube.geojson"
    PropertyMapping:
      image: "${base_url}/images/outside-cube/${ID}.jpg"

Styles:
  - Identifier: default
    ColorMappings:
      conc_chl:
        ColorBar: "plasma"
        ValueRange: [0., 24.]
      conc_tsm:
        ColorBar: "PuBuGn"
        ValueRange: [0., 100.]
      kd489:
        ColorBar: "jet"
        ValueRange: [0., 6.]
      rgb:
        Red:
          Variable: conc_chl
          ValueRange: [0., 24.]
        Green:
          Variable: conc_tsm
          ValueRange: [0., 100.]
        Blue:
          Variable: kd489
          ValueRange: [0., 6.]

ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Norman Fomferra"
    PositionName: "Senior Software Engineer"
    ContactInfo:
      Phone:
        Voice: "+49 4152 889 303"
        Facsimile: "+49 4152 889 330"
      Address:
        DeliveryPoint: "HZG / GITZ"
        City: "Geesthacht"
        AdministrativeArea: "Herzogtum Lauenburg"
        PostalCode: "21502"
        Country: "Germany"
        ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"
